#!/bin/sh

# Share your current tmux session with other users easily and securely
#
# Author: Michal Sojka <michal.sojka@cvut.cz>

help() {
    cat <<EOF
Usage: tmux-share LOGIN
       tmux-share -x

Share current tmux session with another user.

  LOGIN   the user to share with
  -x      disable sharing and disconnect all other clients

Report bugs to https://github.com/wentasah/tmux-share/issues.
EOF
}

set -e

: ${TMUX:?Error: This must be run from within tmux}

socket_path=$(tmux list-sessions -F '#{socket_path}' | head -n1)
: ${socket_path:?Cannot determine tmux socket path}

case "$1" in
    ""|-h|--help)
	help
	exit 1
	;;
    -x)
	setfacl --remove-all "${socket_path}"
	setfacl --remove-all "${socket_path%/*}"
	tmux detach-client -a	# Detach all other clients
	echo >&2 "Unshared"
	exit 0
	;;
    *)
	guest_user=${1:?No user specified}
	setfacl -m u:"$guest_user":rw "${socket_path}"
	setfacl -m u:"$guest_user":rX "${socket_path%/*}"
	;;
esac

attach_cmd="tmux -S $(printf %s "$socket_path") attach"

write "$guest_user" <<EOF || :
You can attach $USER's session by running:

    $attach_cmd

Append "-r" for read-only access.
EOF

cat <<EOF
Now, $guest_user can attach your session by running:

    $attach_cmd

Append "-r" for read-only access.
EOF
